server:
  port: 80

#数据库
spring:
  datasource:
    url: jdbc:mysql://47.112.180.64:3306/myg?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: fly030473
    driver-class-name: com.mysql.cj.jdbc.Driver

#解决使用Mybatis时，如果查询语句中某些字段值是null的，则这个字段就无法返回。
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lpf.ecs_springboot.entity


#主键策略和基本配置
#ID_WORKER是默认的全局主键策略  表示全局主键都采用该策略（如果全局策略和局部策略都有设置，局部策略优先级高）
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    #如不设置，查询到的结果为null 则属性不显示
    call-setters-on-nulls: true
  type-aliases-package: com.lpf.ecs_springboot.entity



#配置逻辑删除标记值
#logic-delete-value: -1        #设置全局逻辑删除标记
#logic-not-delete-value: 0


logging:
  config: classpath:logback-spring.xml
  path: logs
  file: admin.log
  level:
    com.lpf.bookkeeping.dao: debug